//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Companies> Companies { get; set; }
    public virtual DbSet<DomainToCompanies> DomainToCompanies { get; set; }
    public virtual DbSet<domainToReadySentense> domainToReadySentense { get; set; }
    public virtual DbSet<eventPics> eventPics { get; set; }
    public virtual DbSet<inProcessPics> inProcessPics { get; set; }
    public virtual DbSet<Languages> Languages { get; set; }
    public virtual DbSet<Masters> Masters { get; set; }
    public virtual DbSet<Menus> Menus { get; set; }
    public virtual DbSet<Pages> Pages { get; set; }
    public virtual DbSet<projectsPics> projectsPics { get; set; }
    public virtual DbSet<ReadySentenses> ReadySentenses { get; set; }
    public virtual DbSet<SiteMessages> SiteMessages { get; set; }
    public virtual DbSet<SiteMessagesToLanguages> SiteMessagesToLanguages { get; set; }
    public virtual DbSet<Texts> Texts { get; set; }
    public virtual DbSet<Theme> Theme { get; set; }
    public virtual DbSet<ThemeJS> ThemeJS { get; set; }
    public virtual DbSet<ThemePics> ThemePics { get; set; }
    public virtual DbSet<ThemeToMasters> ThemeToMasters { get; set; }
    public virtual DbSet<MenuToDomain> MenuToDomain { get; set; }
    public virtual DbSet<DomainsList> DomainsList { get; set; }
    public virtual DbSet<Events> Events { get; set; }
    public virtual DbSet<inProcess> inProcess { get; set; }
    public virtual DbSet<Paints> Paints { get; set; }
    public virtual DbSet<projects> projects { get; set; }
    public virtual DbSet<Contacts> Contacts { get; set; }
    public virtual DbSet<Articles> Articles { get; set; }
    public virtual DbSet<ArticlesPics> ArticlesPics { get; set; }
    public virtual DbSet<ArticleToArticlePics> ArticleToArticlePics { get; set; }
}
