//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Articles
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Articles()
    {
        this.ArticleToArticlePics = new HashSet<ArticleToArticlePics>();
    }

    public int ID { get; set; }
    public string content { get; set; }
    public System.DateTime dateIn { get; set; }
    public int domainListID { get; set; }

    public virtual DomainsList DomainsList { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArticleToArticlePics> ArticleToArticlePics { get; set; }
}

public partial class ArticlesPics
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ArticlesPics()
    {
        this.ArticleToArticlePics = new HashSet<ArticleToArticlePics>();
    }

    public int ID { get; set; }
    public string fileName { get; set; }
    public System.DateTime dateIn { get; set; }
    public int domainListID { get; set; }

    public virtual DomainsList DomainsList { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArticleToArticlePics> ArticleToArticlePics { get; set; }
}

public partial class ArticleToArticlePics
{
    public int ID { get; set; }
    public int articleID { get; set; }
    public int articlePicsID { get; set; }
    public System.DateTime dateIn { get; set; }

    public virtual Articles Articles { get; set; }
    public virtual ArticlesPics ArticlesPics { get; set; }
}

public partial class Companies
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Companies()
    {
        this.DomainToCompanies = new HashSet<DomainToCompanies>();
    }

    public int ID { get; set; }
    public string email { get; set; }
    public string password { get; set; }
    public System.Guid companyGuid { get; set; }
    public System.DateTime dateIn { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DomainToCompanies> DomainToCompanies { get; set; }
}

public partial class Contacts
{
    public int contactID { get; set; }
    public string name { get; set; }
    public string email { get; set; }
    public string message { get; set; }
    public System.DateTime date_in { get; set; }
    public int domainListID { get; set; }

    public virtual DomainsList DomainsList { get; set; }
}

public partial class DomainsList
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DomainsList()
    {
        this.DomainToCompanies = new HashSet<DomainToCompanies>();
        this.domainToReadySentense = new HashSet<domainToReadySentense>();
        this.Events = new HashSet<Events>();
        this.inProcess = new HashSet<inProcess>();
        this.MenuToDomain = new HashSet<MenuToDomain>();
        this.Paints = new HashSet<Paints>();
        this.projects = new HashSet<projects>();
        this.Contacts = new HashSet<Contacts>();
        this.Articles = new HashSet<Articles>();
        this.ArticlesPics = new HashSet<ArticlesPics>();
        this.ThemePics = new HashSet<ThemePics>();
    }

    public int ID { get; set; }
    public string url { get; set; }
    public System.DateTime dateIn { get; set; }
    public int themeID { get; set; }
    public int languageID { get; set; }
    public Nullable<int> defaultPageID { get; set; }
    public string logo { get; set; }

    public virtual Languages Languages { get; set; }
    public virtual Theme Theme { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DomainToCompanies> DomainToCompanies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<domainToReadySentense> domainToReadySentense { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Events> Events { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<inProcess> inProcess { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MenuToDomain> MenuToDomain { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Paints> Paints { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<projects> projects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Contacts> Contacts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Articles> Articles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArticlesPics> ArticlesPics { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThemePics> ThemePics { get; set; }
}

public partial class DomainToCompanies
{
    public int ID { get; set; }
    public int companyID { get; set; }
    public int domainID { get; set; }
    public System.DateTime dateIn { get; set; }

    public virtual Companies Companies { get; set; }
    public virtual DomainsList DomainsList { get; set; }
}

public partial class domainToReadySentense
{
    public int ID { get; set; }
    public int readySentensesID { get; set; }
    public System.DateTime dateIn { get; set; }
    public int domainListID { get; set; }
    public string description { get; set; }

    public virtual ReadySentenses ReadySentenses { get; set; }
    public virtual DomainsList DomainsList { get; set; }
}

public partial class eventPics
{
    public int id { get; set; }
    public int eventID { get; set; }
    public string eventImage { get; set; }
    public string engDescription { get; set; }
    public int domainListID { get; set; }
}

public partial class Events
{
    public int eventID { get; set; }
    public string eventName { get; set; }
    public string eventPlace { get; set; }
    public string eventText { get; set; }
    public string eventDate { get; set; }
    public int domainListID { get; set; }

    public virtual DomainsList DomainsList { get; set; }
}

public partial class inProcess
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public inProcess()
    {
        this.inProcessPics = new HashSet<inProcessPics>();
    }

    public int inProcessID { get; set; }
    public string inProcessName { get; set; }
    public string inProcessPlace { get; set; }
    public string inProcessText { get; set; }
    public string inProcessDate { get; set; }
    public int domainListID { get; set; }

    public virtual DomainsList DomainsList { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<inProcessPics> inProcessPics { get; set; }
}

public partial class inProcessPics
{
    public int id { get; set; }
    public int inProcessID { get; set; }
    public string inProcessImage { get; set; }
    public string engDescription { get; set; }

    public virtual inProcess inProcess { get; set; }
}

public partial class Languages
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Languages()
    {
        this.SiteMessagesToLanguages = new HashSet<SiteMessagesToLanguages>();
        this.DomainsList = new HashSet<DomainsList>();
    }

    public int ID { get; set; }
    public string language { get; set; }
    public string localLanguage { get; set; }
    public string CurrentCulture { get; set; }
    public string direction { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SiteMessagesToLanguages> SiteMessagesToLanguages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DomainsList> DomainsList { get; set; }
}

public partial class Masters
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Masters()
    {
        this.Theme = new HashSet<Theme>();
        this.ThemeToMasters = new HashSet<ThemeToMasters>();
    }

    public int ID { get; set; }
    public string name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Theme> Theme { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThemeToMasters> ThemeToMasters { get; set; }
}

public partial class Menus
{
    public int ID { get; set; }
    public int pageID { get; set; }
    public int name { get; set; }
    public int menuType { get; set; }

    public virtual Pages Pages { get; set; }
    public virtual SiteMessages SiteMessages { get; set; }
    public virtual SiteMessages SiteMessages1 { get; set; }
}

public partial class MenuToDomain
{
    public byte ID { get; set; }
    public int domainListID { get; set; }
    public string linkName { get; set; }
    public int menuType { get; set; }
    public int pageID { get; set; }
    public int isInternal { get; set; }
    public int apperOrder { get; set; }
    public string PageTitle { get; set; }
    public byte visibility { get; set; }

    public virtual Pages Pages { get; set; }
    public virtual SiteMessages SiteMessages { get; set; }
    public virtual DomainsList DomainsList { get; set; }
}

public partial class Pages
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pages()
    {
        this.Menus = new HashSet<Menus>();
        this.ReadySentenses = new HashSet<ReadySentenses>();
        this.ThemePics = new HashSet<ThemePics>();
        this.MenuToDomain = new HashSet<MenuToDomain>();
    }

    public int ID { get; set; }
    public string pageLink { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Menus> Menus { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ReadySentenses> ReadySentenses { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThemePics> ThemePics { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MenuToDomain> MenuToDomain { get; set; }
}

public partial class Paints
{
    public int paintID { get; set; }
    public string paintName { get; set; }
    public string paintDescription { get; set; }
    public string paintSize { get; set; }
    public string paintImage { get; set; }
    public string engName { get; set; }
    public string engDescription { get; set; }
    public bool isMain { get; set; }
    public string remarks { get; set; }
    public bool isSold { get; set; }
    public int position { get; set; }
    public int category { get; set; }
    public int domainListID { get; set; }

    public virtual DomainsList DomainsList { get; set; }
}

public partial class projects
{
    public int projectsID { get; set; }
    public string projectsName { get; set; }
    public string projectsPlace { get; set; }
    public string projectsText { get; set; }
    public string projectsDate { get; set; }
    public int domainListID { get; set; }

    public virtual DomainsList DomainsList { get; set; }
}

public partial class projectsPics
{
    public int id { get; set; }
    public int projectsID { get; set; }
    public string projectsImage { get; set; }
    public string engDescription { get; set; }
    public Nullable<System.DateTime> dateIn { get; set; }
}

public partial class ReadySentenses
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ReadySentenses()
    {
        this.domainToReadySentense = new HashSet<domainToReadySentense>();
    }

    public int ID { get; set; }
    public System.DateTime dateIn { get; set; }
    public string textKey { get; set; }
    public int pageID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<domainToReadySentense> domainToReadySentense { get; set; }
    public virtual Pages Pages { get; set; }
}

public partial class SiteMessages
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SiteMessages()
    {
        this.Menus = new HashSet<Menus>();
        this.Menus1 = new HashSet<Menus>();
        this.SiteMessagesToLanguages = new HashSet<SiteMessagesToLanguages>();
        this.MenuToDomain = new HashSet<MenuToDomain>();
    }

    public int ID { get; set; }
    public string message { get; set; }
    public System.DateTime dateIn { get; set; }
    public Nullable<int> dataType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Menus> Menus { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Menus> Menus1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SiteMessagesToLanguages> SiteMessagesToLanguages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MenuToDomain> MenuToDomain { get; set; }
}

public partial class SiteMessagesToLanguages
{
    public int ID { get; set; }
    public string message { get; set; }
    public Nullable<int> siteMessageID { get; set; }
    public Nullable<int> languageID { get; set; }
    public Nullable<System.DateTime> dateIn { get; set; }

    public virtual Languages Languages { get; set; }
    public virtual SiteMessages SiteMessages { get; set; }
}

public partial class Texts
{
    public int textID { get; set; }
    public string textName { get; set; }
    public string text { get; set; }
    public int domainListID { get; set; }
    public string imageFile { get; set; }
}

public partial class Theme
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Theme()
    {
        this.ThemeJS = new HashSet<ThemeJS>();
        this.ThemePics = new HashSet<ThemePics>();
        this.ThemeToMasters = new HashSet<ThemeToMasters>();
        this.DomainsList = new HashSet<DomainsList>();
    }

    public int ID { get; set; }
    public string name { get; set; }
    public int masterPageID { get; set; }

    public virtual Masters Masters { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThemeJS> ThemeJS { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThemePics> ThemePics { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThemeToMasters> ThemeToMasters { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DomainsList> DomainsList { get; set; }
}

public partial class ThemeJS
{
    public int ID { get; set; }
    public int themeID { get; set; }
    public string fileName { get; set; }
    public int isInternal { get; set; }
    public byte isActive { get; set; }

    public virtual Theme Theme { get; set; }
}

public partial class ThemePics
{
    public int ID { get; set; }
    public string fileName { get; set; }
    public int themeID { get; set; }
    public int pageID { get; set; }
    public string imgID { get; set; }
    public Nullable<int> domainListID { get; set; }
    public Nullable<System.DateTime> dateIn { get; set; }

    public virtual Pages Pages { get; set; }
    public virtual Theme Theme { get; set; }
    public virtual DomainsList DomainsList { get; set; }
}

public partial class ThemeToMasters
{
    public int ID { get; set; }
    public int themeID { get; set; }
    public int masterID { get; set; }

    public virtual Masters Masters { get; set; }
    public virtual Theme Theme { get; set; }
}
